@extends('layouts.main')

@section('content')
<canvas id="calendar-bg" class="fixed inset-0 -z-10"></canvas>

<main class="min-h-screen pt-8 pb-20 px-4 relative">
    <!-- Header -->
    <div class="text-center mb-12 z-10 relative">
        <h1 class="text-5xl md:text-6xl font-black text-[#384D95] mb-2">Kalender Catatan</h1>
        <p class="text-[#384D95] opacity-70 font-medium">Catat momen penting & dokumentasikan hari-harimu ✨</p>
    </div>

    <!-- Calendar Container -->
    <div class="max-w-5xl mx-auto z-10 relative">
        <!-- Month Navigation -->
        <div class="flex items-center justify-between mb-8 bg-white/80 backdrop-blur-sm p-6 rounded-2xl shadow-lg border border-white/20">
            <button id="prevMonth" class="w-12 h-12 rounded-full bg-[#384D95] hover:bg-[#E63E88] text-white flex items-center justify-center transition-all hover:scale-110 shadow-md font-bold text-xl">
                ❮
            </button>
            <div class="text-center flex-1">
                <h2 id="monthYear" class="text-3xl font-black text-[#384D95] mb-1"></h2>
                <p class="text-sm text-[#384D95] opacity-60">Klik tanggal untuk menambah catatan</p>
            </div>
            <button id="nextMonth" class="w-12 h-12 rounded-full bg-[#384D95] hover:bg-[#E63E88] text-white flex items-center justify-center transition-all hover:scale-110 shadow-md font-bold text-xl">
                ❯
            </button>
        </div>

        <!-- Days of Week Header -->
        <div class="grid grid-cols-7 gap-2 mb-2">
            <div class="text-center font-black text-[#384D95] text-sm py-3">SEN</div>
            <div class="text-center font-black text-[#384D95] text-sm py-3">SEL</div>
            <div class="text-center font-black text-[#384D95] text-sm py-3">RAB</div>
            <div class="text-center font-black text-[#384D95] text-sm py-3">KAM</div>
            <div class="text-center font-black text-[#384D95] text-sm py-3">JUM</div>
            <div class="text-center font-black text-[#E63E88] text-sm py-3 font-bold">SAB</div>
            <div class="text-center font-black text-[#E63E88] text-sm py-3 font-bold">MIN</div>
        </div>

        <!-- Calendar Grid -->
        <div id="calendarGrid" class="grid grid-cols-7 gap-2 mb-12">
            <!-- Days will be generated by JS -->
        </div>

        <!-- Legend -->
        <div class="bg-white/80 backdrop-blur-sm p-6 rounded-2xl shadow-lg border border-white/20 mb-8">
            <h3 class="font-bold text-[#384D95] mb-4">📋 Warna Catatan:</h3>
            <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
                <div class="flex items-center gap-2">
                    <div class="w-6 h-6 rounded-full bg-[#E63E88] shadow-md"></div>
                    <span class="text-sm text-[#384D95] font-medium">Penting</span>
                </div>
                <div class="flex items-center gap-2">
                    <div class="w-6 h-6 rounded-full bg-[#384D95] shadow-md"></div>
                    <span class="text-sm text-[#384D95] font-medium">Belajar</span>
                </div>
                <div class="flex items-center gap-2">
                    <div class="w-6 h-6 rounded-full bg-[#FFB84D] shadow-md"></div>
                    <span class="text-sm text-[#384D95] font-medium">Reminder</span>
                </div>
                <div class="flex items-center gap-2">
                    <div class="w-6 h-6 rounded-full bg-[#4CAF50] shadow-md"></div>
                    <span class="text-sm text-[#384D95] font-medium">Selesai</span>
                </div>
            </div>
        </div>

        <!-- Notes Preview -->
        <div class="bg-white/80 backdrop-blur-sm p-8 rounded-2xl shadow-lg border border-white/20">
            <h3 id="selectedDateTitle" class="text-2xl font-black text-[#384D95] mb-6">Pilih tanggal untuk melihat catatan</h3>
            <div id="notesContainer" class="space-y-3 max-h-96 overflow-y-auto">
                <!-- Notes will be displayed here -->
            </div>
        </div>
    </div>
</main>

<!-- Modal Tambah/Edit Catatan -->
<div id="noteModal" class="hidden fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4 backdrop-blur-sm">
    <div class="bg-white rounded-3xl shadow-2xl max-w-lg w-full p-8 transform transition-all animate-bounce-in">
        <h2 id="modalTitle" class="text-3xl font-black text-[#384D95] mb-6">Tambah Catatan</h2>
        
        <div class="mb-6">
            <label class="block text-sm font-bold text-[#384D95] mb-3">Tanggal</label>
            <p id="modalDate" class="text-lg font-bold text-[#E63E88]"></p>
        </div>

        <div class="mb-6">
            <label class="block text-sm font-bold text-[#384D95] mb-3">Kategori</label>
            <div class="flex flex-wrap gap-2">
                <button class="category-btn px-4 py-2 rounded-full font-bold transition-all text-sm" data-category="important" style="background-color: #E63E88; color: white;">
                    🔴 Penting
                </button>
                <button class="category-btn px-4 py-2 rounded-full font-bold transition-all text-sm" data-category="learning" style="background-color: #E8E8FF; color: #384D95;">
                    📚 Belajar
                </button>
                <button class="category-btn px-4 py-2 rounded-full font-bold transition-all text-sm" data-category="reminder" style="background-color: #FFE8CC; color: #D97706;">
                    ⏰ Reminder
                </button>
                <button class="category-btn px-4 py-2 rounded-full font-bold transition-all text-sm" data-category="done" style="background-color: #E8F5E9; color: #2E7D32;">
                    ✓ Selesai
                </button>
            </div>
            <input type="hidden" id="selectedCategory" value="important">
        </div>

        <div class="mb-6">
            <label class="block text-sm font-bold text-[#384D95] mb-3">Catatan</label>
            <textarea id="noteText" placeholder="Tulis catatan kamu di sini..." class="w-full p-4 border-2 border-[#384D95] rounded-xl focus:outline-none focus:ring-2 focus:ring-[#E63E88] focus:border-transparent resize-none h-32 font-medium text-[#384D95]"></textarea>
        </div>

        <div class="flex gap-3">
            <button id="deletNoteBtn" class="flex-1 bg-red-500/20 text-red-600 py-3 rounded-xl font-bold transition-all hover:bg-red-500/30 hidden">
                🗑️ Hapus
            </button>
            <button id="closeModal" class="flex-1 bg-gray-200 text-[#384D95] py-3 rounded-xl font-bold transition-all hover:bg-gray-300">
                Batal
            </button>
            <button id="saveNote" class="flex-1 bg-[#E63E88] text-white py-3 rounded-xl font-bold transition-all hover:bg-[#d42d74] hover:scale-105 shadow-md">
                💾 Simpan
            </button>
        </div>
    </div>
</div>

<style>
    @keyframes slideInDown {
        from {
            opacity: 0;
            transform: translateY(-30px);
        }
        to {
            opacity: 1;
            transform: translateY(0);
        }
    }

    @keyframes fadeInScale {
        from {
            opacity: 0;
            transform: scale(0.9);
        }
        to {
            opacity: 1;
            transform: scale(1);
        }
    }

    @keyframes bounce-in {
        0% {
            opacity: 0;
            transform: scale(0.95) translateY(-20px);
        }
        70% {
            transform: scale(1.02);
        }
        100% {
            opacity: 1;
            transform: scale(1) translateY(0);
        }
    }

    .animate-bounce-in {
        animation: bounce-in 0.5s ease-out;
    }

    .calendar-day {
        aspect-ratio: 1;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        cursor: pointer;
        border-radius: 1.5rem;
        font-weight: bold;
        transition: all 0.3s ease;
        position: relative;
        background: white/70;
        backdrop-filter: blur(10px);
        border: 2px solid transparent;
        animation: fadeInScale 0.6s ease-out forwards;
    }

    .calendar-day:nth-child(n) {
        animation-delay: calc(var(--day-index, 0) * 0.02s);
    }

    .calendar-day.other-month {
        opacity: 0.35;
        cursor: default;
    }

    .calendar-day.today {
        background: linear-gradient(135deg, #E63E88, #d42d74);
        color: white;
        border-color: #E63E88;
        box-shadow: 0 8px 20px rgba(230, 62, 136, 0.3);
        transform: scale(1.05);
    }

    .calendar-day.has-note {
        border-color: #384D95;
        box-shadow: 0 4px 12px rgba(56, 77, 149, 0.2);
    }
/* deym */
    .calendar-day.has-note::before {
        content: '';
        position: absolute;
        bottom: 4px;
        width: 6px;
        height: 6px;
        border-radius: 50%;
        background-color: currentColor;
    }

    .calendar-day:hover:not(.other-month) {
        transform: translateY(-4px) scale(1.08);
        box-shadow: 0 12px 24px rgba(56, 77, 149, 0.2);
        border-color: #E63E88;
    }

    .calendar-day.selected {
        background: linear-gradient(135deg, #384D95, #2a3a6a);
        color: white;
        border-color: white;
    }

    .day-number {
        font-size: 1.125rem;
        color: #384D95;
    }

    .calendar-day.today .day-number,
    .calendar-day.selected .day-number {
        color: white;
    }

    .note-indicator {
        font-size: 0.75rem;
        margin-top: 2px;
    }

    .note-item {
        padding: 1rem;
        border-radius: 1rem;
        animation: slideInDown 0.4s ease-out;
        border-left: 4px solid;
    }

    .note-item.important {
        background-color: #FFE5F0;
        border-left-color: #E63E88;
    }

    .note-item.learning {
        background-color: #E8E8FF;
        border-left-color: #384D95;
    }

    .note-item.reminder {
        background-color: #FFE8CC;
        border-left-color: #FFB84D;
    }

    .note-item.done {
        background-color: #E8F5E9;
        border-left-color: #4CAF50;
    }

    .note-text {
        color: #384D95;
        font-weight: 500;
        word-break: break-word;
    }

    .note-category {
        font-size: 0.75rem;
        font-weight: bold;
        margin-bottom: 0.5rem;
        opacity: 0.7;
    }

    .category-btn.active {
        opacity: 1;
        transform: scale(1.1);
        box-shadow: 0 6px 12px rgba(0, 0, 0, 0.15);
    }

    .category-btn:not(.active) {
        opacity: 0.6;
    }

    #notesContainer {
        scrollbar-width: thin;
        scrollbar-color: #E63E88 #f0f0f0;
    }

    #notesContainer::-webkit-scrollbar {
        width: 8px;
    }

    #notesContainer::-webkit-scrollbar-track {
        background: #f0f0f0;
        border-radius: 10px;
    }

    #notesContainer::-webkit-scrollbar-thumb {
        background: #E63E88;
        border-radius: 10px;
    }

    #notesContainer::-webkit-scrollbar-thumb:hover {
        background: #d42d74;
    }
</style>

<script>
    // Canvas Background
    const canvas = document.getElementById('calendar-bg');
    const ctx = canvas.getContext('2d');

    function resizeCanvas() {
        canvas.width = window.innerWidth;
        canvas.height = window.innerHeight;
    }
    resizeCanvas();
    window.addEventListener('resize', resizeCanvas);

    function drawBackground() {
        const gradient = ctx.createLinearGradient(0, 0, canvas.width, canvas.height);
        gradient.addColorStop(0, '#FAFBFF');
        gradient.addColorStop(0.5, '#F5F7FF');
        gradient.addColorStop(1, '#FAFBFF');
        ctx.fillStyle = gradient;
        ctx.fillRect(0, 0, canvas.width, canvas.height);

        ctx.globalAlpha = 0.1;
        ctx.strokeStyle = '#E63E88';
        ctx.lineWidth = 2;
        for (let i = 0; i < 3; i++) {
            const x = canvas.width * (0.3 + Math.sin(Date.now() * 0.0002 + i) * 0.2);
            const y = canvas.height * (0.4 + Math.cos(Date.now() * 0.0002 + i) * 0.2);
            const r = 100 + Math.sin(Date.now() * 0.0001 + i) * 50;
            ctx.beginPath();
            ctx.arc(x, y, r, 0, Math.PI * 2);
            ctx.stroke();
        }
        ctx.globalAlpha = 1;
    }

    function animate() {
        drawBackground();
        requestAnimationFrame(animate);
    }
    animate();

    // Calendar Logic
    const monthYearEl = document.getElementById('monthYear');
    const calendarGrid = document.getElementById('calendarGrid');
    const noteModal = document.getElementById('noteModal');
    const noteText = document.getElementById('noteText');
    const saveNoteBtn = document.getElementById('saveNote');
    const closeModalBtn = document.getElementById('closeModal');
    const deletNoteBtn = document.getElementById('deletNoteBtn');
    const selectedDateTitle = document.getElementById('selectedDateTitle');
    const notesContainer = document.getElementById('notesContainer');
    const modalDate = document.getElementById('modalDate');
    const modalTitle = document.getElementById('modalTitle');

    let currentDate = new Date();
    let selectedDate = null;
    let selectedNote = null;
    let notes = JSON.parse(localStorage.getItem('calendarNotes')) || {};

    const monthNames = ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'];
    const categoryColors = {
        important: '#E63E88',
        learning: '#384D95',
        reminder: '#FFB84D',
        done: '#4CAF50'
    };

    function renderCalendar() {
        const year = currentDate.getFullYear();
        const month = currentDate.getMonth();

        monthYearEl.textContent = `${monthNames[month]} ${year}`;

        const firstDay = new Date(year, month, 1);
        const lastDay = new Date(year, month + 1, 0);
        const prevLastDay = new Date(year, month, 0);
        const nextDays = 7 - lastDay.getDay() - 1;

        const prevDaysArray = Array.from({length: firstDay.getDay()}, (_, i) => {
            return prevLastDay.getDate() - firstDay.getDay() + 1 + i;
        });

        const currentDaysArray = Array.from({length: lastDay.getDate()}, (_, i) => i + 1);
        const nextDaysArray = Array.from({length: nextDays}, (_, i) => i + 1);

        const allDays = [...prevDaysArray, ...currentDaysArray, ...nextDaysArray];

        calendarGrid.innerHTML = '';
        allDays.forEach((day, index) => {
            const dayEl = document.createElement('div');
            dayEl.className = 'calendar-day';
            dayEl.style.setProperty('--day-index', index);

            const isCurrentMonth = index >= firstDay.getDay() && index < firstDay.getDay() + lastDay.getDate();
            const displayMonth = !isCurrentMonth ? (index < firstDay.getDay() ? month - 1 : month + 1) : month;
            const displayYear = !isCurrentMonth && displayMonth === -1 ? year - 1 : !isCurrentMonth && displayMonth === 12 ? year + 1 : year;

            if (!isCurrentMonth) {
                dayEl.classList.add('other-month');
            }

            const today = new Date();
            const cellDate = new Date(displayYear, displayMonth, day);
            const isToday = cellDate.toDateString() === today.toDateString();

            if (isToday) {
                dayEl.classList.add('today');
            }

            const dateKey = cellDate.toISOString().split('T')[0];
            if (notes[dateKey] && notes[dateKey].length > 0) {
                dayEl.classList.add('has-note');
            }

            dayEl.innerHTML = `
                <div class="day-number">${day}</div>
                ${notes[dateKey] && notes[dateKey].length > 0 ? `<div class="note-indicator">●</div>` : ''}
            `;

            if (isCurrentMonth) {
                dayEl.addEventListener('click', () => openNoteModal(cellDate));
            }

            calendarGrid.appendChild(dayEl);
        });
    }

    function openNoteModal(date) {
        selectedDate = date;
        selectedNote = null;
        const dateKey = date.toISOString().split('T')[0];
        const dayName = ['Minggu', 'Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu'][date.getDay()];
        const formattedDate = `${dayName}, ${date.getDate()} ${monthNames[date.getMonth()]} ${date.getFullYear()}`;

        modalDate.textContent = formattedDate;
        modalTitle.textContent = 'Tambah Catatan';
        noteText.value = '';
        document.getElementById('selectedCategory').value = 'important';
        deletNoteBtn.classList.add('hidden');

        // Reset category buttons
        document.querySelectorAll('.category-btn').forEach(btn => {
            btn.classList.remove('active');
            if (btn.dataset.category === 'important') {
                btn.classList.add('active');
            }
        });

        noteModal.classList.remove('hidden');
    }

    function closeNoteModalFunc() {
        noteModal.classList.add('hidden');
    }

    function saveNoteFunc() {
        const dateKey = selectedDate.toISOString().split('T')[0];
        const category = document.getElementById('selectedCategory').value;
        const text = noteText.value.trim();

        if (!text) {
            alert('Tulis catatan terlebih dahulu!');
            return;
        }

        if (!notes[dateKey]) {
            notes[dateKey] = [];
        }

        if (selectedNote !== null) {
            notes[dateKey][selectedNote] = {category, text};
        } else {
            notes[dateKey].push({category, text});
        }

        localStorage.setItem('calendarNotes', JSON.stringify(notes));
        renderCalendar();
        displayNotes(selectedDate);
        closeNoteModalFunc();
    }

    function displayNotes(date) {
        const dateKey = date.toISOString().split('T')[0];
        const dayName = ['Minggu', 'Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu'][date.getDay()];
        const formattedDate = `${dayName}, ${date.getDate()} ${monthNames[date.getMonth()]} ${date.getFullYear()}`;

        selectedDateTitle.textContent = formattedDate;
        notesContainer.innerHTML = '';

        const dateNotes = notes[dateKey];
        if (!dateNotes || dateNotes.length === 0) {
            notesContainer.innerHTML = '<p class="text-[#384D95] opacity-60 text-center py-8">Belum ada catatan untuk hari ini 📝</p>';
            return;
        }

        dateNotes.forEach((note, index) => {
            const noteEl = document.createElement('div');
            noteEl.className = `note-item ${note.category}`;
            const categoryLabels = {
                important: '🔴 Penting',
                learning: '📚 Belajar',
                reminder: '⏰ Reminder',
                done: '✓ Selesai'
            };

            noteEl.innerHTML = `
                <div class="note-category">${categoryLabels[note.category]}</div>
                <div class="note-text">${note.text}</div>
                <div class="flex gap-2 mt-3 justify-end">
                    <button class="edit-btn text-xs px-3 py-1 rounded bg-white/50 hover:bg-white font-bold transition-all" data-index="${index}">✏️ Edit</button>
                    <button class="delete-btn text-xs px-3 py-1 rounded bg-red-500/20 text-red-600 hover:bg-red-500/30 font-bold transition-all" data-index="${index}">🗑️</button>
                </div>
            `;

            notesContainer.appendChild(noteEl);
        });

        document.querySelectorAll('.edit-btn').forEach(btn => {
            btn.addEventListener('click', (e) => {
                selectedNote = parseInt(e.target.dataset.index);
                const note = notes[dateKey][selectedNote];
                noteText.value = note.text;
                document.getElementById('selectedCategory').value = note.category;
                document.querySelectorAll('.category-btn').forEach(b => b.classList.remove('active'));
                document.querySelector(`[data-category="${note.category}"]`).classList.add('active');
                modalTitle.textContent = 'Edit Catatan';
                deletNoteBtn.classList.remove('hidden');
                noteModal.classList.remove('hidden');
            });
        });

        document.querySelectorAll('.delete-btn').forEach(btn => {
            btn.addEventListener('click', (e) => {
                const index = parseInt(e.target.dataset.index);
                notes[dateKey].splice(index, 1);
                if (notes[dateKey].length === 0) delete notes[dateKey];
                localStorage.setItem('calendarNotes', JSON.stringify(notes));
                renderCalendar();
                displayNotes(selectedDate);
            });
        });
    }

    document.getElementById('prevMonth').addEventListener('click', () => {
        currentDate.setMonth(currentDate.getMonth() - 1);
        renderCalendar();
    });

    document.getElementById('nextMonth').addEventListener('click', () => {
        currentDate.setMonth(currentDate.getMonth() + 1);
        renderCalendar();
    });

    document.querySelectorAll('.category-btn').forEach(btn => {
        btn.addEventListener('click', () => {
            document.querySelectorAll('.category-btn').forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
            document.getElementById('selectedCategory').value = btn.dataset.category;
        });
    });

    saveNoteBtn.addEventListener('click', saveNoteFunc);
    closeModalBtn.addEventListener('click', closeNoteModalFunc);

    deletNoteBtn.addEventListener('click', () => {
        const dateKey = selectedDate.toISOString().split('T')[0];
        if (selectedNote !== null) {
            notes[dateKey].splice(selectedNote, 1);
            if (notes[dateKey].length === 0) delete notes[dateKey];
            localStorage.setItem('calendarNotes', JSON.stringify(notes));
            renderCalendar();
            displayNotes(selectedDate);
            closeNoteModalFunc();
        }
    });

    // Calendar Default View
    const today = new Date();
    const todayElement = document.querySelector('.calendar-day.today');
    if (todayElement) {
        todayElement.click();
    }

    renderCalendar();
    displayNotes(today);

    // Close modal saat klik background
    noteModal.addEventListener('click', (e) => {
        if (e.target === noteModal) {
            closeNoteModalFunc();
        }
    });
</script>
@endsection
